version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      WHITELIST: ~
      OVERRIDE_OPS: "true"
      OPS: ~
      MAX_PLAYERS: 20
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./data/minecraft:/data